adminprofilpasienpendonor/urls.py
from django.urls import path
from . import views

app_name = 'adminprofilpasienpendonor'

urlpatterns = [
	path('', views.admin_list_patient_donor, name='admin_list_patient_donor'),

	path('profil-pendonor/', views.donor_profile, name='donor_profile'),
	path('profil-pasien/', views.patient_profile, name='patient_profile'),

	path('download/<str:file_name>/', views.download, name='download'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

sidoplak/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('akun/', include('users.urls')),
    path('admin-sidoplak/daftar-pasien-pendonor/', include('adminprofilpasienpendonor.urls')),
    path('admin-sidoplak/verifikasi-pasangan/', include('adminverifikasipasangan.urls')),
    path('profildiri/', include('profildiri.urls')),
    path('forum/', include('forum.urls')),
    path('daftarPasien/', include('daftarPasien.urls')),
    path('daftar/', include('daftar.urls')),
    path('artikel/', include('artikel.urls')),
    path('tinymce/', include('tinymce.urls')),
]

adminprofilpasienpendonor/models.py
from django.db import models

# Create your models here.

adminprofilpasienpendonor/forms.py
from django import forms

from .constants import get_address_province_as_form_choices
from users.models import USER_ROLE_CHOICES


ADDRESS_PROVINCE_FILTER_CHOICES = get_address_province_as_form_choices("--Provinsi--")
BLOOD_TYPE_FILTER_CHOICES = (('', "--Goldar--"), ('A+', "A+"), ('A-', "A-"), ('B+', "B+"), ('B-', "B-"), ('O+', "O+"), ('O-', "O-"), ('AB+', "AB+"), ('AB-', "AB-"),)
SHOW_FILTER_CHOICES = (('10', '10 entri'), ('15', '15 entri'), ('20', '20 entri'), ('50', '50 entri'), ('semua', 'Semua entri'),)


class FiltersForm(forms.Form):
	show = forms.ChoiceField(required = False, choices=SHOW_FILTER_CHOICES, widget=forms.Select(attrs={'type' : 'text', 'class' : 'form-text-control'}))
	fil_prov = forms.ChoiceField(required = False, choices=ADDRESS_PROVINCE_FILTER_CHOICES, widget=forms.Select(attrs={'type' : 'text', 'class' : 'form-text-control'}))
	fil_goldar = forms.ChoiceField(required = False, choices=BLOOD_TYPE_FILTER_CHOICES, widget=forms.Select(attrs={'type' : 'text', 'class' : 'form-text-control'}))
	fil_role = forms.ChoiceField(required = False, choices=USER_ROLE_CHOICES, widget=forms.Select(attrs={'type' : 'text', 'class' : 'form-text-control'}))
	search_name = forms.CharField(required = False, max_length=255, widget=forms.TextInput(attrs={'type' : 'text', 'placeholder' : 'Cari nama', 'class' : 'form-text-control', 'autocomplete' : 'off'}))
	search_patient = forms.CharField(required = False, max_length=255, widget=forms.TextInput(attrs={'type' : 'text', 'placeholder' : 'Cari nama pasien', 'class' : 'form-text-control', 'autocomplete' : 'off'}))
	search_donor = forms.CharField(required = False, max_length=255, widget=forms.TextInput(attrs={'type' : 'text', 'placeholder' : 'Cari nama pendonor', 'class' : 'form-text-control', 'autocomplete' : 'off'}))

adminprofilpasienpendonor/views.py
from django.shortcuts import render, redirect
from django.http import Http404, HttpResponse
from django.conf import settings
from django.contrib import messages

from daftar.models import Pasien, Pendonor
from .forms import FiltersForm

import zipfile
import io
import os
import urllib.parse


def admin_list_patient_donor(request):
	if not request.user.is_admin():
		raise Http404

	#GET parameters init
	page = 1
	show = 10
	fil_prov = None
	fil_goldar = None
	fil_role = None
	search_name = None

	url_param = "" #Create URL get parameter for page viewing

	if request.GET:
		if "page" in request.GET:
			if request.GET['page'].isdigit():
				page = int(request.GET['page'])
		if "fil_role" in request.GET:
			fil_role = request.GET['fil_role']
			url_param += f"fil_role={fil_role}&"
		if "show" in request.GET:
			if request.GET['show'].isdigit():
				show = int(request.GET['show'])
				url_param += f"show={str(show)}&"
			elif request.GET['show'] == "semua":
				if fil_role == "PENDONOR":
					show = Pendonor.objects.count()
				else:
					show = Pasien.objects.count()
				url_param += f"show=semua&"
		if "fil_prov" in request.GET:
			fil_prov = request.GET['fil_prov']
			url_param += f"fil_prov={fil_prov}&"
		if "fil_goldar" in request.GET:
			fil_goldar = request.GET['fil_goldar']
			url_param += f"fil_goldar={fil_goldar}&"
		if "search_name" in request.GET:
			search_name = request.GET['search_name']
			url_param += f"search_name={search_name}&"
	elif request.POST:
		page = 1
		if "fil_role" in request.POST:
			if request.POST['fil_role'] != "":
				fil_role = request.POST['fil_role']
				url_param += f"fil_role={fil_role}&"
		if "show" in request.POST:
			if request.POST['show'] != "" and request.POST['show'].isdigit():
				show = int(request.POST['show'])
				url_param += f"show={str(show)}&"
			elif request.POST['show'] == "semua":
				if fil_role == "PENDONOR":
					show = Pendonor.objects.count()
				else:
					show = Pasien.objects.count()
				url_param += f"show=semua&"
		if "fil_prov" in request.POST:
			if request.POST['fil_prov'] != "":
				fil_prov = request.POST['fil_prov']
				url_param += f"fil_prov={fil_prov}&"
		if "fil_goldar" in request.POST:
			if request.POST['fil_goldar'] != "":
				fil_goldar = request.POST['fil_goldar']
				url_param += f"fil_goldar={fil_goldar}&"
		if "search_name" in request.POST:
			if request.POST['search_name'] != "":
				search_name = request.POST['search_name']
				url_param += f"search_name={search_name}&"

	url_param = url_param.replace("+", "%2B") #URL encoding

	if show <= 0:
		show = 1


	#set filter for query
	if fil_role == "PENDONOR":
		# filter on Pendonor model
		users_to_be_shown = Pendonor.objects.all()
	else:
		# filter on Pasien model
		users_to_be_shown = Pasien.objects.all()

	if fil_prov is not None:
		users_to_be_shown = users_to_be_shown.filter(address_province=fil_prov)
	if fil_goldar is not None:
		goldar = fil_goldar[:-1]
		rhesus = fil_goldar[-1:]
		users_to_be_shown = users_to_be_shown.filter(medical_blood_type=goldar).filter(medical_rhesus=rhesus)
	if search_name is not None:
		users_to_be_shown = users_to_be_shown.filter(full_name__icontains=search_name)

	#number of pages
	num_of_users_to_be_shown = users_to_be_shown.count()
	num_of_pages = int(num_of_users_to_be_shown / show) + (num_of_users_to_be_shown % show > 0)

	# If page requested is out of the available pages, raise Http404
	if (page <= 0 or page > num_of_pages) and num_of_pages != 0:
		raise Http404

	list_page_number_bar = []
	for i in range(-1, 2):
		page_number_bar = page + i
		if page_number_bar > 0 and page_number_bar <= num_of_pages:
			list_page_number_bar.append(page_number_bar)

	is_there_more_pages_left = False
	is_there_more_pages_right = False
	if (page - 2) > 0:
		is_there_more_pages_left = True
	if (page + 2) <= num_of_pages:
		is_there_more_pages_right = True

	# Get objects
	idx_start = show * (page-1)
	idx_end = show * page
	if fil_role == "PENDONOR":
		# if role is pendonor, set result to donors and let patients be None
		donors = users_to_be_shown.select_related('user').order_by("-timestamp_last_request")[idx_start:idx_end]
		patients = None
	else:
		# if role is not pendonor, set result to patients and let donors be None
		donors = None
		patients = users_to_be_shown.select_related('user').order_by("-timestamp_last_request")[idx_start:idx_end]


	# Filter Form
	form = FiltersForm(request.POST or None)
	
	if show == num_of_users_to_be_shown:
		form.fields['show'].initial = "semua"
	else:
		form.fields['show'].initial = show
	if fil_prov is not None:
		form.fields['fil_prov'].initial = fil_prov
	if fil_goldar is not None:
		form.fields['fil_goldar'].initial = fil_goldar
	if fil_role == "PENDONOR":
		form.fields['fil_role'].initial = "PENDONOR"
	else:
		form.fields['fil_role'].initial = "PASIEN"
	if search_name is not None:
		form.fields['search_name'].initial = search_name

	context = {
		'form' : form,
		'patients' : patients,
		'donors' : donors,
		'list_page_number_bar' : list_page_number_bar,
		'page' : page,
		'num_of_pages' : num_of_pages,
		'url_param' : url_param,
		'is_there_more_pages_left' : is_there_more_pages_left,
		'is_there_more_pages_right' : is_there_more_pages_right,
	}

	return render(request, "adminprofilpasienpendonor/admin_list_patient_donor.html", context)



def patient_profile(request):
	if not request.user.is_admin():
		raise Http404

	pk = None
	if "pk" in request.GET:
		pk = request.GET['pk']

	patient = Pasien.objects.filter(user__email=pk).select_related('user')
	if patient:
		patient = patient.first()
		donor_applications = patient.donor_applications.order_by("-timestamp_created")
	else:
		raise Http404

	return render(request, "adminprofilpasienpendonor/patient_profile.html", {
		'patient' : patient,
		'donor_applications' : donor_applications,
	})



def donor_profile(request):
	if not request.user.is_admin():
		raise Http404

	pk = None
	if "pk" in request.GET:
		pk = request.GET['pk']


	donor = Pendonor.objects.filter(user__email=pk)
	if donor:
		donor = donor.first()
	else:
		raise Http404

	return render(request, "adminprofilpasienpendonor/donor_profile.html", {
		'donor' : donor,
	})



def download(request, file_name):
	if not request.user.is_superuser:
		raise Http404

	file_name = urllib.parse.unquote(file_name)
	file_name = urllib.parse.unquote(file_name)
	file_name = file_name.replace("/media/", "", 1)

	if os.path.isfile(settings.MEDIA_ROOT / file_name):
		zip_subdir = file_name[file_name.rfind("/")+1:file_name.rfind(".")].replace("/", "_")
		zip_filename = "%s.zip" % zip_subdir
		return download_as_zip([file_name], zip_subdir, zip_filename)
	else:
		return HttpResponse("FILE NOT FOUND: Heroku tidak mendukung unggahan file lama karena akan dihapus secara berkala pada filesystemnya.")




''' CUSTOM FUNCTION '''

def download_as_zip(filenames, zip_subdir, zip_filename):
	# Open StringIO to grab in-memory ZIP contents
	s = io.BytesIO()

	# The zip compressor
	zf = zipfile.ZipFile(s, "w")

	media_root = settings.MEDIA_ROOT
	for fpath in filenames:
		fpath = media_root / fpath
		# Calculate path for file in zip
		fdir, fname = os.path.split(fpath)
		zip_path = os.path.join(zip_subdir, fname)

		# Add file, at correct path
		zf.write(fpath, zip_path)

	# Must close zip for all contents to be written
	zf.close()

	# Grab ZIP file from in-memory, make response with correct MIME-type
	response = HttpResponse(s.getvalue(), content_type = "application/x-zip-compressed")
	response['Content-Disposition'] = 'attachment; filename=%s' % zip_filename

	return response

adminprofilpasienpendonor/templates/adminprofilpasienpendonor/admin_list_patient_donor.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>List Profil Pasien dan Pendonor | SIDOPLAK</title>
<link rel="stylesheet" href="{% static 'adminprofilpasienpendonor/css/style.css' %}">
<script type="application/javascript" src="{% static 'adminprofilpasienpendonor/js/script.js' %}"></script>
{% endblock meta %}

{% block content %}
    <div class="content-admin">
    	<div class="content-list-patient-donor">
	    	<h1>Pasien dan Pendonor</h1>
	    	<form method="POST" class="form form-filter-container" action="{% url 'adminprofilpasienpendonor:admin_list_patient_donor' %}">
	    		{% csrf_token %}

	    		<div class="form-filter-field-horizontal-container">
		    		<div class="form-filter-field">
		    			<label>Entri/Hal :</label>
			    		{{ form.show }}
			    		{{ form.show.errors }}
		    		</div>

		    		<div class="form-filter-field form-text-control search-bar">
			    		{{ form.search_name }}
			    		{{ form.search_name.errors }}
			    		<label for="button-submit-search">
				    		<svg width="30" width="30" viewBox="0 0 24 24">
					    		<use href="{% static 'base/svg/base-sprite-sheet.svg' %}#search-icon"></use>
					    	</svg>
					    </label>
		    			<button type="submit" class="button" id="button-submit-search">Cari</button>
		    		</div>
	    		</div>

    			<div class="form-filter-field" style="margin-top: 1em;">
	    			<label>Filter :</label>
		    		{{ form.fil_prov }}
		    		{{ form.fil_prov.errors }}

		    		{{ form.fil_goldar }}
		    		{{ form.fil_goldar.errors }}

		    		{{ form.fil_role }}
		    		{{ form.fil_role.errors }}
		    		<button type="submit" class="button" id="button-submit">Terapkan</button>
	    		</div>
	    	</form>
	    	<div class="list-container">
    			<div class="list-bar" id="list-bar-header">
    				<p>Nama Lengkap</p>
	        		<p>Provinsi</p>
	        		<p class="justify-self-center">Gol. Darah</p>
	        		<p class="justify-self-center">Jenis Kel.</p>
	        		<a class="button" disabled>Download</a>
    			</div>

    			{% if not patients and not donors %}
    				<h2 style="margin: 1.252em 0; width: 100%; text-align: center;">
    					{{ form.fil_role.initial|slice:":1" }}<span style="text-transform: lowercase;">{{ form.fil_role.initial|slice:"1:" }}</span> Yang Dicari Tidak Ditemukan
    				</h2>
    			{% endif %}
		        {% for patient in patients %}
		        	<div href="{% url 'adminprofilpasienpendonor:patient_profile' %}?pk={{ patient.user.email }}" class="list-bar list-patient-bar">
		        		<p>{{ patient.full_name|truncatechars:20 }}</p>
		        		<p>{{ patient.address_province }}</p>
		        		<p class="justify-self-center">{{ patient.medical_blood_type }}{{ patient.medical_rhesus }}</p>
		        		{% if patient.gender == 'LAKI-LAKI' %}
		        			<p class="justify-self-center">
		        				<svg width="30" height="30" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <use href="#outline-male" width="30" height="30"/>
                                </svg>
		        			</p>
		        		{% elif patient.gender == 'PEREMPUAN' %}
		        			<p class="justify-self-center">
		        				<svg width="30" height="30" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <use href="#outline-female" width="30" height="30"/>
                                </svg>
		        			</p>
		        		{% endif %}
		        	</div>
		        {% endfor %}
		        {% for donor in donors %}
		        	<div href="{% url 'adminprofilpasienpendonor:donor_profile' %}?pk={{ donor.user.email }}" class="list-bar list-donor-bar">
		        		<p>{{ donor.full_name|truncatechars:20 }}</p>
		        		<p>{{ donor.address_province }}</p>
		        		<p class="justify-self-center">{{ donor.medical_blood_type }}{{ donor.medical_rhesus }}</p>
		        		{% if donor.gender == 'LAKI-LAKI' %}
		        			<p class="justify-self-center">
		        				<svg width="30" height="30" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <use href="#outline-male" width="30" height="30"/>
                                </svg>
		        			</p>
		        		{% elif donor.gender == 'PEREMPUAN' %}
		        			<p class="justify-self-center">
		        				<svg width="30" height="30" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <use href="#outline-female" width="30" height="30"/>
                                </svg>
		        			</p>
		        		{% endif %}
		        	</div>
		        {% endfor %}
		    </div>
		    <div class="pagination">
		    	{% if page != 1 %}
		    		<a href="{% url 'adminprofilpasienpendonor:admin_list_patient_donor' %}?page={{ page|add:'-1' }}&{{ url_param }}">&lt</a>
		    	{% endif %}
		    	{% if is_there_more_pages_left %}
		    		<a href="{% url 'adminprofilpasienpendonor:admin_list_patient_donor' %}?page=1&{{ url_param }}">1</a>
		    		<p>...</p>
		    	{% endif %}
		    	{% for page_number_bar in list_page_number_bar %}
		    		{% if page_number_bar == page %}
		    			<p>{{ page_number_bar }}</p>
		    		{% else %}
		    			<a href="{% url 'adminprofilpasienpendonor:admin_list_patient_donor' %}?page={{ page_number_bar }}&{{ url_param }}">{{ page_number_bar }}</a>
		    		{% endif %}
		    	{% endfor %}
		    	{% if is_there_more_pages_right %}
		    		<p>...</p>
		    		<a href="{% url 'adminprofilpasienpendonor:admin_list_patient_donor' %}?page={{ num_of_pages }}&{{ url_param }}">{{ num_of_pages }}</a>
		    	{% endif %}
		    	{% if page != num_of_pages and num_of_pages != 0 %}
		    		<a href="{% url 'adminprofilpasienpendonor:admin_list_patient_donor' %}?page={{ page|add:'1' }}&{{ url_param }}">&gt</a>
		    	{% endif %}
		    </div>
	    </div>

	    <svg style="display: none;" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
			<path id="outline-male" d="M12 11C9.23858 11 7 13.2386 7 16C7 18.7614 9.23858 21 12 21C14.7614 21 17 18.7614 17 16C17 13.2386 14.7614 11 12 11ZM12 11V3M12 3L16 7M12 3L8 7" stroke="#001A72" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
		</svg>
		<svg style="display: none;" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
			<path id="outline-female" d="M12 13C14.7614 13 17 10.7614 17 8C17 5.23858 14.7614 3 12 3C9.23858 3 7 5.23858 7 8C7 10.7614 9.23858 13 12 13ZM12 13L12 21M9 18L15 18" stroke="#d4639b" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
		</svg>
    </div>
{% endblock content %}

adminprofilpasienpendonor/templates/adminprofilpasienpendonor/donor_profile.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Profil Pendonor</title>
<link rel="stylesheet" href="{% static 'adminprofilpasienpendonor/css/style.css' %}">
<script type="application/javascript" src="{% static 'adminprofilpasienpendonor/js/script.js' %}"></script>
{% endblock meta %}

{% block content %}
    <div class="content-admin">
    	<div class="content-donor-profile">

            <div class="bread-crumb-container">
                <a onclick="history.back();"><span>&lt</span> Kembali</a>
            </div>

    		<h1>Pendonor {{ donor.full_name }}</h1>
            <div class="profile-card">
                <div>
                    <div>
                        <div>
                            <label>Nama Lengkap</label>
                            <p>{{ donor.full_name }}</p>
                        </div>
                        <div>
                            <label>Email</label>
                            <p style="word-break: break-all;">{{ donor.user.email }}</p>
                        </div>
                        <div>
                            <label>NIK</label>
                            <p>{{ donor.nik }}</p>
                        </div>
                        <div>
                            <label>No HP</label>
                            <p>{{ donor.nohp }}</p>
                        </div>
                        <div>
                            <label>Jenis Kelamin</label>
                            <p>{{ donor.gender }}</p>
                        </div>
                        <div>
                            <label>Tempat Lahir</label>
                            <p>{{ donor.place_of_birth }}</p>
                        </div>
                        <div>
                            <label>Tanggal Lahir</label>
                            <p>{{ donor.date_of_birth }}</p>
                        </div>       
                    </div>
                    <div>
                        <div>
                            <label>Pekerjaan</label>
                            <p>{{ donor.profession }}</p>
                        </div>
                        <div>
                            <label>Alamat Domisili</label>
                            <p>{{ donor.get_full_address }}</p>
                        </div>
                        <div>
                            <label>Golongan Darah</label>
                            <p>{{ donor.get_full_blood_type }}</p>
                        </div>
                        <div>
                            <label>Berat Badan</label>
                            <p>{{ donor.medical_weight }} kg</p>
                        </div>
                        <div>
                            <label>Tinggi Badan</label>
                            <p>{{ donor.medical_height }} cm</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="patient-donor-data-buttons">
            	{% if donor.file_pcr_positive %}
	            	<a href="{% url 'adminprofilpasienpendonor:download' donor.file_pcr_positive.url|urlencode:'' %}" class="button">
					Download Berkas PCR Positif
					</a>
				{% endif %}
            	{% if donor.file_pcr_negative %}
					<a href="{% url 'adminprofilpasienpendonor:download' donor.file_pcr_negative.url|urlencode:'' %}" class="button">
						Download Berkas PCR Negatif
					</a>
				{% endif %}
            </div>

    	</div>
    </div>
{% endblock content %}

adminprofilpasienpendonor/templates/adminprofilpasienpendonor/patient_profile.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Profil Pasien</title>
<link rel="stylesheet" href="{% static 'adminprofilpasienpendonor/css/style.css' %}">
<script type="application/javascript" src="{% static 'adminprofilpasienpendonor/js/script.js' %}"></script>
{% endblock meta %}

{% block content %}
    <div class="content-admin">
    	<div class="content-patient-profile">

            <div class="bread-crumb-container">
                <a onclick="history.back();"><span>&lt</span> Kembali</a>
            </div>

    		<h1>Pasien {{ patient }}</h1>
            <div class="profile-card">
                <div>
                    <div>
                        <div>
                            <label>Nama Lengkap</label>
                            <p>{{ patient.full_name }}</p>
                        </div>
                        <div>
                            <label>Email</label>
                            <p style="word-break: break-all;">{{ patient.user.email }}</p>
                        </div>
                        <div>
                            <label>NIK</label>
                            <p>{{ patient.nik }}</p>
                        </div>
                        <div>
                            <label>No HP</label>
                            <p>{{ patient.nohp }}</p>
                        </div>
                        <div>
                            <label>Jenis Kelamin</label>
                            <p>{{ patient.gender }}</p>
                        </div>
                        <div>
                            <label>Tempat Lahir</label>
                            <p>{{ patient.place_of_birth }}</p>
                        </div>
                        <div>
                            <label>Tanggal Lahir</label>
                            <p>{{ patient.date_of_birth }}</p>
                        </div>       
                    </div>
                    <div>
                        <div>
                            <label>Pekerjaan</label>
                            <p>{{ patient.profession }}</p>
                        </div>
                        <div>
                            <label>Alamat Domisili</label>
                            <p>{{ patient.get_full_address }}</p>
                        </div>
                        <div>
                            <label>Golongan Darah</label>
                            <p>{{ patient.get_full_blood_type }}</p>
                        </div>
                        <div>
                            <label>Berat Badan</label>
                            <p>{{ patient.medical_weight }} kg</p>
                        </div>
                        <div>
                            <label>Tinggi Badan</label>
                            <p>{{ patient.medical_height }} cm</p>
                        </div>
                    </div>
                </div>
            </div>

        	{% for donor_application in donor_applications %}
        		{% if donor_application.file %}
		            <div class="patient-donor-data-buttons">
		        		<a href="{% url 'adminprofilpasienpendonor:download' donor_application.file.url|urlencode:'' %}" class="button">
							Download Berkas Pasien (ID: {{ donor_application.id }})
						</a>
		            </div>
	            {% endif %}
			{% endfor %}
    	</div>
    </div>
{% endblock content %}