artikel/urls.py
from django.urls import path
from . import views

app_name = 'artikel'

urlpatterns = [
	path('', views.main, name='main'),
	path('buat', views.buat, name='buat'),
	path('lihat', views.lihat, name='lihat'),
	path('edit', views.edit, name='edit'),
	path('delete', views.delete, name='delete'),
]

daftar/urls.py
from django.urls import path

from . import views

app_name = 'daftar'

urlpatterns = [
    path('', views.daftar, name='daftar'),
    path('pasien', views.daftarPasien, name='daftarPasien'),
    path('pendonor', views.daftarPendonor, name='daftarPendonor'),
]

forum/urls.py
from django.urls import path
from . import views

app_name = 'forum'

urlpatterns = [
    path('', views.listforum, name='listforum'),
    path('create/', views.create, name='create'),
    path('detail/<int:idx>/', views.detail, name='detail'),
    path('update/<int:idx>/', views.update, name='update'),
    path('delete/<int:idx>/', views.delete, name='delete'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

sidoplak/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('akun/', include('users.urls')),
    path('admin-sidoplak/daftar-pasien-pendonor/', include('adminprofilpasienpendonor.urls')),
    path('admin-sidoplak/verifikasi-pasangan/', include('adminverifikasipasangan.urls')),
    path('profildiri/', include('profildiri.urls')),
    path('forum/', include('forum.urls')),
    path('daftarPasien/', include('daftarPasien.urls')),
    path('daftar/', include('daftar.urls')),
    path('artikel/', include('artikel.urls')),
    path('tinymce/', include('tinymce.urls')),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signUp, name='signup'),
    path('login/', views.auth_login, name='login'),
    path('logout/', views.auth_logout, name='logout'),
    path('profile/', views.profile, name='profile'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static 'base/css/style.css' %}">
	<link rel="shortcut icon" href="{% static 'base/img/favicon.png' %}"/>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script type="application/javascript" src="{% static 'base/js/script.js' %}"></script>
	{% block meta %}
	{% endblock meta %}
</head>

<body>
	<header {% if '/' == request.path %}class="header header-transparent"{% else %}class="header header-white"{% endif %}>
		<a href="{% url 'main:home' %}" class="logo"><img src="{% static 'base/img/sidoplak-logo.png' %}" style="width:9rem; height:3rem;"></a>
		<input type="checkbox" class="nav-toggle" id="nav-toggle">

		<nav>
			<ul>
				{% if request.user.is_admin %}
					<li class="nav-only-desktop"><a href="" id="admin-mode">ADMIN</a></li>
				{% endif %}
				{% if request.user.is_authenticated and not request.user.is_admin %}
					<li><a href="{% url 'daftar:daftar' %}">Pendaftaran</a></li>
				{% endif %}
				{% if request.user.is_authenticated %}
					<li><a href="{% url 'daftarPasien:daftarPasien' %}">List Pasien</a></li>
				{% endif %}
				<li><a href="{% url 'forum:listforum' %}">Forum</a></li>
                <li><a href="{% url 'artikel:main' %}">Artikel</a></li>
				{% if request.user.is_admin %}
					<li class="nav-only-desktop nav-user-container">
						<div class="nav-user">
							<a class="dropdown-btn">
								Admin
								<svg width="12" height="8" version="2.0">
									<use href="{% static 'base/svg/base-sprite-sheet.svg' %}#arrow-down"/>
								</svg>
							</a>
							<div class="dropdown-content-container">
								<a href="{% url 'adminprofilpasienpendonor:admin_list_patient_donor' %}" class="dropdown-content dashboard" style="border-bottom: 1px black solid;">
									List Pasien dan Pendonor
								</a>
								<a href="{% url 'adminverifikasipasangan:list_match' %}" class="dropdown-content dashboard">
									Verifikasi Pasangan
								</a>
							</div>
						</div>
					</li>
					<li class="nav-only-mobile"><a href="{% url 'adminprofilpasienpendonor:admin_list_patient_donor' %}">List Pasien dan Pendonor</a></li>
					<li class="nav-only-mobile"><a href="{% url 'adminverifikasipasangan:list_match' %}">Verifikasi Pasangan</a></li>
				{% endif %}
				{% if user.is_authenticated %}
					<li class="nav-only-desktop nav-user-container">
						<div class="nav-user">
							<a class="dropdown-btn">
								<svg width="12" height="12" version="2.0">
									<use href="{% static 'base/svg/person.svg' %}#svg-person"/>
								</svg>
								{{ user.nickname }}
								<svg width="12" height="8" version="2.0">
									<use href="{% static 'base/svg/base-sprite-sheet.svg' %}#arrow-down"/>
								</svg>
							</a>
							<div class="dropdown-content-container">
								<a href="{% url 'profildiri:profildiri' %}" class="dropdown-content dashboard" style="border-bottom: 1px black solid;">
									<svg class="icon-dashboard" width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
										<path fill-rule="evenodd" clip-rule="evenodd" d="M7 10H1C0.45 10 0 9.55 0 9V1C0 0.45 0.45 0 1 0H7C7.55 0 8 0.45 8 1V9C8 9.55 7.55 10 7 10ZM7 18H1C0.45 18 0 17.55 0 17V13C0 12.45 0.45 12 1 12H7C7.55 12 8 12.45 8 13V17C8 17.55 7.55 18 7 18ZM11 18H17C17.55 18 18 17.55 18 17V9C18 8.45 17.55 8 17 8H11C10.45 8 10 8.45 10 9V17C10 17.55 10.45 18 11 18ZM10 5V1C10 0.45 10.45 0 11 0H17C17.55 0 18 0.45 18 1V5C18 5.55 17.55 6 17 6H11C10.45 6 10 5.55 10 5Z" fill="black"/>
									</svg>
									Profil
								</a>
								<a href="{% url 'users:logout' %}" class="dropdown-content logout">
									<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
										<path d="M16 13V11H7V8L2 12L7 16V13H16Z" fill="#999999"/>
										<path d="M20 3H11C9.897 3 9 3.897 9 5V9H11V5H20V19H11V15H9V19C9 20.103 9.897 21 11 21H20C21.103 21 22 20.103 22 19V5C22 3.897 21.103 3 20 3Z" fill="#999999"/>
									</svg>
									Keluar
								</a>
							</div>
						</div>
					</li>
					<div class="nav-dropdown-buttons nav-only-mobile">
					   <a href="{% url 'profildiri:profildiri' %}" class="nav-only-mobile button btn-dashboard">
							<svg width="24" height="24">
								<path id="dashboard-icon" fill-rule="evenodd" clip-rule="evenodd" d="M7 10H1C0.45 10 0 9.55 0 9V1C0 0.45 0.45 0 1 0H7C7.55 0 8 0.45 8 1V9C8 9.55 7.55 10 7 10ZM7 18H1C0.45 18 0 17.55 0 17V13C0 12.45 0.45 12 1 12H7C7.55 12 8 12.45 8 13V17C8 17.55 7.55 18 7 18ZM11 18H17C17.55 18 18 17.55 18 17V9C18 8.45 17.55 8 17 8H11C10.45 8 10 8.45 10 9V17C10 17.55 10.45 18 11 18ZM10 5V1C10 0.45 10.45 0 11 0H17C17.55 0 18 0.45 18 1V5C18 5.55 17.55 6 17 6H11C10.45 6 10 5.55 10 5Z" fill="black"/>
							</svg>
							Profil
						</a>
						<a href="{% url 'users:logout' %}" class="nav-only-mobile button btn-keluar">
							<svg width="24" height="24">
								<path id="log-out-1" d="M16 13V11H7V8L2 12L7 16V13H16Z" fill="#EC4E43"/>
								<path id="log-out-2" d="M20 3H11C9.897 3 9 3.897 9 5V9H11V5H20V19H11V15H9V19C9 20.103 9.897 21 11 21H20C21.103 21 22 20.103 22 19V5C22 3.897 21.103 3 20 3Z" fill="#EC4E43"/>
							</svg>
							Keluar
						</a>
					</div>
				{% else %}
				<li class="nav-only-desktop">
						<a href="{% url 'users:signup' %}" class="button fit-content height-fit-content" style="margin: 0; padding: 0.6em 1em;">Daftar</a>
					</li>
					<li class="nav-only-desktop">
						<a href="{% url 'users:login' %}" class="button fit-content height-fit-content" style="margin: 0; padding: 0.6em 1em;">Masuk</a>
					</li>
					<div class="nav-dropdown-buttons nav-only-mobile">
						<a href="{% url 'users:signup' %}" class="nav-only-mobile button btn-dashboard">
							Daftar
						</a>
					</div>
					<div class="nav-dropdown-buttons nav-only-mobile">
						<a href="{% url 'users:login' %}" class="nav-only-mobile button btn-dashboard">
							Masuk
						</a>
					</div>
				{% endif %}
			</ul>
		</nav>

		{% if user.is_authenticated %}
            <div class="nav2">
                <ul>
                	{% if request.user.is_admin %}
						<li><a href="" id="admin-mode">ADMIN</a></li>
					{% endif %}
                </ul>
            </div>
        {% endif %}

		<label for="nav-toggle" class="nav-toggle-label" id="nav-toggle-label"><span></span></label>
		
	</header>

	<div class="content-container">
		{% if messages %}
			{% for message in messages %}
				{% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
					<div class="messages success-msg">
						 <svg width="20" height="20">
							<use href="{% static 'base/svg/base-sprite-sheet.svg' %}#success-msg"/>
						</svg>
						{{ message }}
						<span class="close-messages">&times;</span>
					</div>
				{% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
					<div class="messages error-msg">
						 <svg width="20" height="20">
							<use href="{% static 'base/svg/base-sprite-sheet.svg' %}#error-msg"/>
						</svg>
						{{ message }}
						<span class="close-messages">&times;</span>
					</div>
				{% else %}
					<div class="messages">
						 <svg width="20" height="20">
							<use href="{% static 'base/svg/base-sprite-sheet.svg' %}#error-msg"/>
						</svg>
						{{ message }}
						<span class="close-messages">&times;</span>
					</div>
				{% endif %}
			{% endfor %}
		{% endif %}
	  	{% block content %}
		{% endblock content %}
	</div>

	<footer class="footer">
		<div class="footer1">
			<a href="{% url 'main:home' %}" class="fit-content"><img src="{% static 'base/img/sidoplak-logo.png' %}" style="width:13rem; height:4rem;"></a>
			<div class="nav-only-desktop" style="margin: 0;">
				<svg width="24" height="24" viewBox="0 0 24 24">
					<use href="{% static 'base/svg/base-sprite-sheet.svg' %}#copyright-logo"></use>
				</svg>
				<p>Sistem Donor Plasma Kovalen</p>
			</div>
		</div>

		<div class="footer2">
			<ul>
				<li>
					<a href="">
						<svg width="32" height="32" viewBox="0 0 24 24">
							<use href="{% static 'base/svg/base-sprite-sheet.svg' %}#facebook-logo"></use>
						</svg>
					</a>
				</li>
				<li>
					<a href="">
						<svg width="32" height="32" viewBox="0 0 24 24">
							<use href="{% static 'base/svg/base-sprite-sheet.svg' %}#line-logo"></use>
						</svg>
					</a>
				</li>
				<li>
					<a href="">
						<svg width="32" height="32" viewBox="0 0 24 24">
							<use href="{% static 'base/svg/base-sprite-sheet.svg' %}#instagram-logo"></use>
						</svg>
					</a>
				</li>
				<li>
					<a href="">
						<svg width="32" height="32" viewBox="0 0 24 24">
							<use href="{% static 'base/svg/base-sprite-sheet.svg' %}#twitter-logo"></use>
						</svg>
					</a>
				</li>
				<li>
					<a href="">
						<svg width="32" height="32" viewBox="0 0 24 24">
							<use href="{% static 'base/svg/base-sprite-sheet.svg' %}#youtube-logo"></use>
						</svg>
					</a>
				</li>
				<li>
					<a href="">
						<svg width="32" height="32" viewBox="0 0 24 24">
							<use href="{% static 'base/svg/base-sprite-sheet.svg' %}#spotify-logo"></use>
						</svg>
					</a>
				</li>
				<li>
					<a href="">
						<svg width="32" height="32" viewBox="0 0 24 24">
							<use href="{% static 'base/svg/base-sprite-sheet.svg' %}#linkedin-logo"></use>
						</svg>
					</a>
				</li>
			</ul>
		</div>

		<div class="footer3 nav-only-mobile" style="margin: 0;">
			<svg width="24" height="24" viewBox="0 0 24 24">
				<use href="{% static 'base/svg/base-sprite-sheet.svg' %}#copyright-logo"></use>
			</svg>
			<p>Sistem Donor Plasma Kovalen</p>
		</div>
	</footer>
</body>

</html>