daftar/urls.py
from django.urls import path

from . import views

app_name = 'daftar'

urlpatterns = [
    path('', views.daftar, name='daftar'),
    path('pasien', views.daftarPasien, name='daftarPasien'),
    path('pendonor', views.daftarPendonor, name='daftarPendonor'),
]

daftarPasien/urls.py
from django.urls import path
from daftar.models import Pasien
from . import views

app_name = 'daftarPasien'

urlpatterns = [
	path('', views.daftarPasien, name='daftarPasien'),
	path('filter/', views.filter, name='filter'),
	path('detailPasienMinimum/', views.detailPasienMinimum, name='detailPasienMinimum'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

sidoplak/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('akun/', include('users.urls')),
    path('admin-sidoplak/daftar-pasien-pendonor/', include('adminprofilpasienpendonor.urls')),
    path('admin-sidoplak/verifikasi-pasangan/', include('adminverifikasipasangan.urls')),
    path('profildiri/', include('profildiri.urls')),
    path('forum/', include('forum.urls')),
    path('daftarPasien/', include('daftarPasien.urls')),
    path('daftar/', include('daftar.urls')),
    path('artikel/', include('artikel.urls')),
    path('tinymce/', include('tinymce.urls')),
]

daftarPasien/models.py
from django.db import models

# Create your models here.

daftarPasien/forms.py
from django import forms

from adminprofilpasienpendonor.constants import get_address_province_as_form_choices
from users.models import USER_ROLE_CHOICES

ADDRESS_PROVINCE_FILTER_CHOICES = get_address_province_as_form_choices("--Provinsi--")
BLOOD_TYPE_FILTER_CHOICES = (('', "--Goldar--"), ('A+', "A+"), ('A-', "A-"), ('B+', "B+"), ('B-', "B-"), ('O+', "O+"), ('O-', "O-"), ('AB+', "AB+"), ('AB-', "AB-"),)


class FiltersForm(forms.Form):
	fil_prov = forms.ChoiceField(required = False, choices=ADDRESS_PROVINCE_FILTER_CHOICES, widget=forms.Select(attrs={'type' : 'text', 'class' : 'form-text-control'}))
	fil_goldar = forms.ChoiceField(required = False, choices=BLOOD_TYPE_FILTER_CHOICES, widget=forms.Select(attrs={'type' : 'text', 'class' : 'form-text-control'}))

daftarPasien/views.py
from django.shortcuts import render
from django.http import Http404
from daftar.models import DonorApplication, DonorApplicationStatus, Pasien , Pendonor
from users.models import CustomUser
from .forms import FiltersForm
import copy

def daftarPasien(request):
	if not request.user.is_authenticated:
		raise Http404

	listPasien = listPasienStatusMencari(Pasien.objects.all())
	form = FiltersForm(request.POST or None)
	context = {
	    'listPasien' : listPasien,
		'form' : form,
	}
	return render(request, 'daftarPasien/daftarPasien.html', context)

def detailPasienMinimum(request):
    if not request.user.is_authenticated:
        raise Http404
    wid = request.GET['wid']
    wid = request.GET['wid']
    dataUser = Pasien.objects.filter(user__email=wid).select_related('user')
    is_Pendonor = 0
    tmp = Pendonor.objects.filter(user=request.user)
    if request.user.role == "PENDONOR" and len(tmp) == 0:
        is_Pendonor = 1
    elif request.user.role == "PENDONOR" and len(tmp) == 1:
        donorStatus = DonorApplication.objects.filter(donor=tmp[0])[0]
        if donorStatus.status.status == "1":
            is_Pendonor = 1
    context = {
        'is_Pendonor' : is_Pendonor,
        'dataUser' : dataUser[0],
        'wid' : wid,
    }
    return render(request,'daftarPasien/detailPasienMinimum.html',context)

def filter(request):
    form = FiltersForm(request.POST)
    if request.method == "POST" and form.is_valid():
        prov = None
        goldar = None
        if "fil_prov" in request.POST:
            prov = request.POST['fil_prov']
        if "fil_goldar" in request.POST:
            goldar = request.POST['fil_goldar']
        listPasien = []
        if goldar and prov:
            listPasien = listPasienStatusMencari(Pasien.objects.filter(address_province=prov,medical_blood_type=goldar[0],medical_rhesus=goldar[1]))
        elif not goldar and prov:
            listPasien = listPasienStatusMencari(Pasien.objects.filter(address_province=prov))
        elif not prov and goldar:
            listPasien = listPasienStatusMencari(Pasien.objects.filter(medical_blood_type=goldar[0],medical_rhesus=goldar[1]))
        else :
            listPasien = listPasienStatusMencari(Pasien.objects.all())
        form = FiltersForm(request.POST or None)
        context = {
            'listPasien' : listPasien,
            'form' : form,
        }
        return render(request, 'daftarPasien/daftarPasien.html', context)
    else:
        raise Http404

def listPasienStatusMencari(listPasien):
    listPasienKembalian = []
    for i in range (len(listPasien)):
        donorTmp = DonorApplication.objects.filter(patient=listPasien[i])
        if not donorTmp:
            continue
        else:
            status = donorTmp[0].status.status
            if status == "1":
                listPasienKembalian.append(listPasien[i])
    return listPasienKembalian

daftarPasien/templates/daftarPasien/daftarPasien.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Daftar Pasien | SIDOPLAK</title>
<link rel="stylesheet" href="{% static 'daftarPasien/css/style.css' %}">
<script type="application/javascript" src="{% static 'daftarPasien/js/toggle.js' %}"></script>
{% endblock meta %}

{% block content %}
<div class="content-patient">
	<div class="content-list-patient">
		<h1>Daftar Pasien</h1>
		<button onclick="toggle()" class="button">Filter</button>
		<div id="filteringDiv" style="display: none">
			<form method="POST" class="form form-filter-container" id="form" action="{% url 'daftarPasien:filter' %}">
				{% csrf_token %}
				<div class="form-filter-field" style="margin-top: 1em;">
					<label>Filter :</label>
					{{ form.fil_prov }}
					{{ form.fil_prov.errors }}
					{{ form.fil_goldar }}
					{{ form.fil_goldar.errors }}
					<button type="submit" class="button" id="button-submit" href="{% url 'daftarPasien:filter' %}">Terapkan</button>
				</div>
			</form>
		</div>
		<div class="list-container">
			<div class="list-bar" id="list-bar-header">
				<p>Nama Lengkap</p>
				<p>Provinsi</p>
				<p class="justify-self-center">Gol. Darah</p>
				<p class="justify-self-center">Jenis Kel.</p>
				<p class="justify-self-center">Detail</p>
			</div>
			{% for patient in listPasien %}
				<div class="list-bar list-patient-bar">
					<p>{{ patient.full_name }}</p>
					<p>{{ patient.address_province }}</p>
					<p class="justify-self-center">{{ patient.get_full_blood_type}}</p>
					{% if patient.gender == 'LAKI-LAKI' %}
						<p class="justify-self-center">
							<svg width="30" height="30" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
								<use href="#outline-male" width="30" height="30"/>
							</svg>
						</p>
					{% elif patient.gender == 'PEREMPUAN' %}
						<p class="justify-self-center">
							<svg width="30" height="30" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
								<use href="#outline-female" width="30" height="30"/>
							</svg>
						</p>
					{% endif %}
					<a href="{% url 'daftarPasien:detailPasienMinimum' %}?wid={{ patient.user.email }}" class="donor-button button">Detail</a>
				</div>
			{% endfor %}
		</div>
	</div>

	<svg style="display: none;" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
		<path id="outline-male" d="M12 11C9.23858 11 7 13.2386 7 16C7 18.7614 9.23858 21 12 21C14.7614 21 17 18.7614 17 16C17 13.2386 14.7614 11 12 11ZM12 11V3M12 3L16 7M12 3L8 7" stroke="#001A72" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
	</svg>
	<svg style="display: none;" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
		<path id="outline-female" d="M12 13C14.7614 13 17 10.7614 17 8C17 5.23858 14.7614 3 12 3C9.23858 3 7 5.23858 7 8C7 10.7614 9.23858 13 12 13ZM12 13L12 21M9 18L15 18" stroke="#d4639b" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
	</svg>
</div>
{% endblock content %}

daftarPasien/templates/daftarPasien/detailPasienMinimum.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>DetailPasien</title>
<link rel="stylesheet" href="{% static 'profildiri/css/style.css' %}">
<link rel="stylesheet" href="{% static 'daftarPasien/css/style.css' %}">
{% endblock meta %}

{% block content %}
<div  class ="home-top" style="background-image: url('{% static "main/img/home-bg.jpg"%}');overflow: hidden;">
<div class="content" style="width: 50%;" >
    <div >
        <h1><center>Profil</center></h1>
        <br><br><br>
        <table class="center">
            <tr>
                <td>Nama:</td>
                <td>{{dataUser.full_name}}</td>
            </tr>


            <tr>
                <td>Jenis Kelamin:</td>
                <td>{{dataUser.gender}}</td>
            </tr>

            <tr>
                <td>Provinsi:</td>
                <td>{{dataUser.address_province}}</td>
            </tr>

            <tr>
                <td>Golongan darah:</td>
                <td>{{dataUser.get_full_blood_type}}</td>
            </tr>

            <tr>
                <td>Berat Badan:</td>
                <td>{{dataUser.medical_height}}</td>
            </tr>

            <tr>
                <td>Tinggi Badan:</td>
                <td>{{dataUser.medical_weight}}</td>
            </tr>
        </table>
    </div>
    <br><br>
    <div style="display:flex;justify-content:space-around">
    <a href="{% url 'daftarPasien:daftarPasien' %}" class="donor-button button" style="width:25%;">Kembali</a>
        {% if is_Pendonor == 1%}
        <a href="{% url 'daftar:daftarPendonor' %}?wid={{ wid }}" class="donor-button button" style="width:25%;background: #00FF00;">Donor</a>
        {% endif %}
    </div>
</div>
</div>
{% endblock content %}